### ISSUE TITLE
编译不了

### ISSUE THREAD

**Issue by cathaychen** [LC-Team/LCUI#16]
github中的代码编译不了，代码不全？第一个错误是LCUI_ScreenInfo没定义，搜索了所有文件都没有该定义

**Comment by lc-soft** [comment]
用的是哪个版本的代码？目前分支上的代码都不能完整通过编译，你可以试试以前发布的代码：https://github.com/LC-Team/LCUI/releases

**Comment by cathaychen** [comment]
用的是master分支最新代码

**Comment by cathaychen** [comment]
v0.15.0版的代码有点老，2013年的

**Comment by cathaychen** [comment]
有没有考虑用配置文件（比如说xml）来生成界面，程序代码专注于业务逻辑

**Comment by lc-soft** [comment]
@cathaychen 有考虑过，现在在弄基础部分，这个以后再弄，看上去到时候也就是调用相关（xml、html之类的）解析库，解析配置文件，然后根据结果自动生成界面，貌似工作量不大。
